### ISSUE TITLE
Set session.cookie.secure = false ?

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/dpdash#1]
Can we do that during `./init.sh` ?

`${state}/dpdash/configs/dpdash.js: config.session.cookie.secure = false;`

https://github.com/PREDICT-DPACC/dpdash/blob/585cb7cba46c2b3cd72432975340d8133dde47d6/singularity/configure.py#L373

**Comment by blms** [comment]
This should only be set to `false` for a development instance, i.e. one where we don't have SSL certs and are running HTTP instead of HTTPS, and no sensitive data is stored in cookies.

The current setting (`true`) is correct for a production instance. Is this set to `false` in the instance currently running on predict?

**Comment by blms** [comment]
Looks like it is. @tashrifbillah we should set this to `true` for the new production instance that we spin up. If cookies stored at `https://predict...` fail to work after that, I'll troubleshoot, as it should not be set to `false` when the cookies contain session data for a live production app.

**Comment by tashrifbillah** [comment]
> Is this set to false in the instance currently running on predict?

Yes, it is. Otherwise, DPDash login does not work. We shall let you troubleshoot this soon.

**Comment by blms** [comment]
References for myself for later troubleshooting:
- [nginx/express config suggestion](https://stackoverflow.com/a/60104026)
- [Express docs](http://expressjs.com/en/resources/middleware/session.html)

**Comment by tashrifbillah** [comment]
> > Is this set to false in the instance currently running on predict?
> 
> Yes, it is. Otherwise, DPDash login does not work. We shall let you troubleshoot this soon.

The issue still persists with the latest container.

**Comment by tashrifbillah** [comment]
Here's the relevant section in the README:

https://github.com/PREDICT-DPACC/dpdash/blob/pnl-devel/README-PNL.md#cookies

**Comment by blms** [comment]
Right, but we should be sending encrypted cookies over HTTPS. Since we have a valid SSL certificate for the `predict` domain, we should be able to send encrypted cookies without a problem (i.e. `secure = true`). So I'll troubleshoot with the links I posted above.
