### ISSUE TITLE
RabbitMQ 3.6.x has reached end of life

### ISSUE THREAD

**Issue by blms** [AMP-SCZ/dpdash#13]
Currently, we install v3.6.9 as part of the Singularity build: https://github.com/PREDICT-DPACC/dpdash/blob/cd11691995b56f70c370f3eaccdc3adb4bfa956d/singularity/Singularity#L31

However, it reached EOL in 2018, and last year, so did 3.7.x (see [changelog](https://www.rabbitmq.com/changelog.html)).

We should upgrade to 3.8.x to use supported versions. I'm happy to do this. Here is the [upgrade guide](https://www.rabbitmq.com/upgrade.html) for reference.

**Comment by tashrifbillah** [comment]
I tried but had to table the work due to a cumbersome [supervisord.conf](https://github.com/PREDICT-DPACC/dpdash/blob/pnl-devel/singularity/supervisord.conf) file involved.

**Comment by blms** [comment]
For now we will continue using the EOL version because newer versions require `root` or `rabbitmq` user to use the CLI tools. This would require `root` privileges for running critical DPDash scripts like `setup.sh` and `init.sh`, which is not currently supported in DPDash.

One solution would be to move all RabbitMQ process management outside of the Singularity container. Then RabbitMQ can be installed, configured, and run anywhere—on the machine running the container, on a separate machine, on a "RabbitMQ as a Service", etc.—and accessed with a URL and credentials.

**Comment by tashrifbillah** [comment]
Removed RabbitMQ for Singularity recipe.
