### ISSUE TITLE
Dates not displaying in subject view

### ISSUE THREAD

**Issue by blms** [AMP-SCZ/dpdash#16]
Apparently, some subjects' dates don't display properly on the x-axis in subject view. This seems to be inconsistent even with different subjects in the same study with identical metadata and data structures.

I see a lot of custom logic regarding date handling so I'm going to look around here:

* https://github.com/PREDICT-DPACC/dpdash/blob/863c6a8147f04363a03025bdf3dd9c6f9782f5ca/utils/dateConverter.js#L1
* https://github.com/PREDICT-DPACC/dpdash/blob/863c6a8147f04363a03025bdf3dd9c6f9782f5ca/views/Matrix.d3.js#L267

I'll work on this pending generation of test data.

**Comment by tashrifbillah** [comment]
Tashrif worked a lot on it at issue #49
