### ISSUE TITLE
MongoDB 3.x EOL

### ISSUE THREAD

**Issue by blms** [AMP-SCZ/dpdash#17]
MongoDB 3.4, the version we install, reached EOL in Jan 2020, and MongoDB 3.6 (the following version) reached EOL this month.

Are we pinned to 3.4 for a reason, like other systems depending on it? I think dpimport will at least need to be checked for deprecations when updating. (That may also require an update to pymongo.) Is there anything else?

<details>

<summary>TODO</summary>
 
- [x] Check DPDash for 3.4-->3.6 deprecations
- [x] Check dpimport for 3.4-->3.6 deprecations
- [x] Install 3.6
- [x] `db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } )`
- [x] Check functionality of DPDash
- [x] Check functionality of dpimport
- [x] `db.adminCommand( { setFeatureCompatibilityVersion: "3.6" } )`
- [x] Check DPDash for 3.6-->4.0 deprecations
- [x] Check dpimport for 3.6-->4.0 deprecations
- [x] Install 4.0
- [x] `db.adminCommand( { setFeatureCompatibilityVersion: "3.6" } )`
- [x] Check functionality of DPDash
- [x] Check functionality of dpimport
- [x] `db.adminCommand( { setFeatureCompatibilityVersion: "4.0" } )`
- [x] Check DPDash for 4.0->4.2 deprecations
- [x] Check dpimport for 4.0-->4.2 deprecations
- [x] Install 4.2
- [x] `db.adminCommand( { setFeatureCompatibilityVersion: "4.0" } )`
- [x] Check functionality of DPDash
- [x] Check functionality of dpimport
- [x] `db.adminCommand( { setFeatureCompatibilityVersion: "4.2" } )`
- [x] Check DPDash for 4.2->4.4 deprecations
- [x] Check dpimport for 4.2-->4.4 deprecations
- [x] Install 4.4
- [x] `db.adminCommand( { setFeatureCompatibilityVersion: "4.2" } )`
- [x] Check functionality of DPDash
- [x] Check functionality of dpimport
- [x] `db.adminCommand( { setFeatureCompatibilityVersion: "4.4" } )`

</details>

**Comment by tashrifbillah** [comment]
Linking #7 that I reported a while back.

**Comment by tashrifbillah** [comment]
Should it be closed since PR #18?

**Comment by blms** [comment]
Nope, that was just the Node.js driver, but MongoDB itself needs to be updated during the image build process now.
https://github.com/PREDICT-DPACC/dpdash/blob/52bf146e4661455ce0a5ba9791d31e7532067042/singularity/Singularity#L45-L51

This is a bit more of an involved process requiring following upgrade guides:
https://docs.mongodb.com/manual/release-notes/3.6-upgrade-standalone/
https://docs.mongodb.com/manual/release-notes/4.0-upgrade-standalone/
https://docs.mongodb.com/manual/release-notes/4.2-upgrade-standalone/
https://docs.mongodb.com/manual/release-notes/4.4-upgrade-standalone/

**Comment by sbouix** [comment]
Is this and #13 resolved with the latest merge?

**Comment by blms** [comment]
They are not, upcoming still.
