### ISSUE TITLE
Admin panel bugs

### ISSUE THREAD

**Issue by blms** [AMP-SCZ/dpdash#20]
- [x] When trying to add someone to a study/site: `Cannot read property 'map' of undefined` at `Admin.react.js:361`
- [x] When trying to change a role: `Cannot read property 'removeAttribute' of null` a material-ui error

Neither functionality is currently possible from the UI. Looking into it now.

**Comment by blms** [comment]
Actually, both work fine in my dev instance, but not in production. @tashrifbillah maybe it's a problem with the production DB? 

1. Adding to study/site: `/api/v1/search/studies` should return a list of studies and status code 200, which it does in my instance. In the production instance, it returns status code 404. It's looking for `mongoData.collection('toc').distinct('study')`. This matches the dev DB: when I use the MongoDB shell command `db.toc.distinct('study')`, I get the expected output (a list of all studies). We need to check this on production and figure out why it isn't the case.
2. Changing role: I don't know why this would be an issue in production but not dev. The only thing I can think is to restart the production server and make sure to use the latest singularity image build.

**Comment by tashrifbillah** [comment]
Okay, now I understand what you mean. Thanks for looking into this.

**Comment by blms** [comment]
No problem. Btw, I should mention, with this:

> make sure to use the latest singularity image build

of course comes the caveat that the new configuration method needs to be used with that build. Which we will need to do eventually anyway, so it might be worth doing now.

Maybe it also makes sense to be running that instance from a shared directory rather than one of our home folders. Then I can handle the configuration, check for errors that appear only in production, etc. But we can discuss in a meeting.

**Comment by blms** [comment]
Fixed by reinstalling.
