### ISSUE TITLE
In quit.sh, only kill related processes

### ISSUE THREAD

**Issue by blms** [AMP-SCZ/dpdash#23]
Don't attempt to kill all `mongo` and `rabbitmq` processes, only the ones that are relevant to the instance.

**Comment by tashrifbillah** [comment]
In my opinion, we should keep it as it is. It was meant for starting afresh.

**Comment by blms** [comment]
I should clarify—I mean that it should still kill `mongo` and `rabbitmq`, just not using `pkill` to kill all processes with that name. It should only kill the PIDs associated with the particular instance. That way, if there are other `mongo` or `rabbitmq` running on the same machine, they will not be inadvertently killed. Probably it should be a command sent to `supervisord`.

**Comment by tashrifbillah** [comment]
> It should only kill the PIDs associated with the particular instance.

Thanks for the clarification. I understand it now. I did notice the caveat when we were working on one machine-multiple instances but did not bother since one user will have permission to kill only their processes.
