### ISSUE TITLE
Add script to renew self-signed SSL certs

### ISSUE THREAD

**Issue by blms** [AMP-SCZ/dpdash#24]
Right now they expire after a year, so they will need to be renewed annually.

**Comment by tashrifbillah** [comment]
I am not sure which ones it is referring to. Our predict.bwh.harvard.edu has certs that I believe expire after a year. Once they do, our RCC admins provide new certs and I edit three certs like these ones:

https://github.com/pnlbwh/hcpep-xnat/blob/main/ssl.conf#L105-L121

**Comment by blms** [comment]
I'm referring to the ones generated and signed here:

https://github.com/PREDICT-DPACC/dpdash/blob/585cb7cba46c2b3cd72432975340d8133dde47d6/singularity/init.sh#L41-L79
