### ISSUE TITLE
Add column to graph table and display the site's short name

### ISSUE THREAD

**Issue by Elkrival** [AMP-SCZ/dpdash#253]
### User stories

As a user on the Individual Chart Page
When I view the chart table
Then I see a column for the "Short Name" that has each site's short name in the table rows

**Comment by justintbaker** [comment]
First column title is not Network, should be "Site Name" (as opposed to "Site Code") which is column 2



![Image](https://github.com/AMP-SCZ/dpdash/assets/19879182/c3b75613-8168-48b5-b114-b624e721ab3d)
