### ISSUE TITLE
Add Sex at Birth filter category

### ISSUE THREAD

**Issue by Elkrival** [AMP-SCZ/dpdash#263]
add an additional Filter category "Sex at Birth":
assessment: form_sociodemographics
variable:  chrdemo_sexassigned with 1=Male, 2=Female
by default both values should be checked

**Comment by mikestone14** [comment]
Is it possible that a subject doesn't have a 1 or a 2 for that variable? I'm wondering if we should have an "unknown" option too.

**Comment by Elkrival** [comment]
Yes good point, apparently for missing we could have NaN as a possible value... 
https://gnardog.slack.com/archives/C03KGHSSTNC/p1677556521045529?thread_ts=1677539780.920589&cid=C03KGHSSTNC

**Comment by mikestone14** [comment]
A subject can be missing....

* when they have all empty values for the assessment variable
* when they have no assessment documents
