### ISSUE TITLE
Automate backups of production MongoDB

### ISSUE THREAD

**Issue by blms** [AMP-SCZ/dpdash#32]
Requested by @sbouix. Some options for this:
1. [Filesystem snapshots](https://docs.mongodb.com/manual/tutorial/backup-with-filesystem-snapshots/)
2. [Back up with `cp` or `rsync`](https://docs.mongodb.com/manual/core/backups/#back-up-with-cp-or-rsync)
3. [Back up with `mongodump`](https://docs.mongodb.com/manual/core/backups/#back-up-with-mongodump)

**Comment by tashrifbillah** [comment]
We also discussed making use of `hostname` in [dpimport/config.yml](https://github.com/PREDICT-DPACC/dpimport/blob/main/examples/config.yml#L9). The idea is that dpimport and csv files will live in a private VM but write database in a public VM. We shall specify the latter through `hostname`. I am yet to test it though.

**Comment by tashrifbillah** [comment]
Reporting progress:

> mongo "mongodb://user:password@rc-predict-partners.org:27017/idgen"

has been successful from another VM. Of course, I had to open `27017/tcp` through firewall at the former VM.

**Comment by tashrifbillah** [comment]
`import.py` to another VM has been successful as well. After this success, `/data/predict/` will no longer need to be mounted on a public VM.

**Comment by tashrifbillah** [comment]
configs, charts, users collections are already being backed up through duply to AWS bucket `predict-mongodb`.
