### ISSUE TITLE
Development tips: Reports

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/dpdash#37]
[This](https://github.com/AMP-SCZ/dpdash/blob/ffcc38a413596f845493efb3ebc7fe32c628b9a6/server/routes/index.js#L58) line is using the following database from `config.js`:

> 25 config.database.mongo.dataDB = "dpdata";

So, [point 3](https://github.com/AMP-SCZ/dpdash/wiki/Development-tips:-Reports#new-report-form) appears to be wrong. Shouldn't that be the `dpdata`?

**Comment by blms** [comment]
Nope, it stores `reports` in `dpdmongo`, defined there as `mongoApp`.

https://github.com/AMP-SCZ/dpdash/blob/ffcc38a413596f845493efb3ebc7fe32c628b9a6/server/routes/index.js#L57

https://github.com/AMP-SCZ/dpdash/blob/ffcc38a413596f845493efb3ebc7fe32c628b9a6/server/routes/index.js#L1185-L1192

We would use `mongoData` in the API endpoint if we wanted to store it in `dpdata`.

You can see that `mongoApp` uses the `dpdmongo` database in `getMongoURI`:

https://github.com/AMP-SCZ/dpdash/blob/ffcc38a413596f845493efb3ebc7fe32c628b9a6/server/utils/mongoUtil.js#L4

`settings.appDb` is configured as `dpdmongo` here:

https://github.com/AMP-SCZ/dpdash/blob/ffcc38a413596f845493efb3ebc7fe32c628b9a6/singularity/configure.py#L332

When `mongoClient.db();` is called without an argument, it uses the database from the URI, in this case `dpdmongo`.
