### ISSUE TITLE
Mail --> Email

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/dpdash#5]
Look at the column header, this discrepancy also appears in mongoDB: `dpdmongo`

---

![image](https://user-images.githubusercontent.com/35086881/112175634-ca171900-8bcd-11eb-8fc1-1b67aba61c93.png)

**Comment by tashrifbillah** [comment]
Feel free to correct this TYPO @blms

**Comment by blms** [comment]
I tried 4 different ways to link it, at least one of them worked 😆
