### ISSUE TITLE
Add hover activity over Study code in the Participants Table

### ISSUE THREAD

**Issue by justintbaker** [AMP-SCZ/dpdash#670]
People have a hard time figuring out which short study names map to the long names.

This feature was requested by Marty (PI).

![Image](https://github.com/AMP-SCZ/dpdash/assets/19879182/e577fec4-e9ab-407d-be05-d629c34a7343)

**Comment by dheshanm** [comment]
Added Tooltip to the right from the site names specified at [server/utils/siteNames.js](https://github.com/AMP-SCZ/dpdash/blob/pnl-devel/server/utils/siteNames.js)

Shows the site code, when no matching entry found on siteNames.js

![Image](https://github.com/AMP-SCZ/dpdash/assets/14181952/f0c8b140-2a4e-4ed2-9b7a-0f7bedadddb4)
