### ISSUE TITLE
illegal option -- t

### ISSUE THREAD

**Issue by Elkrival** [AMP-SCZ/dpdash#69]
While running the init.sh script there is an illegal flag error.
`cp: illegal option -- t
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory`

the line in the file reads as 
`find ./ -type f -maxdepth 1 ! -name $DPDASH_IMG -exec cp -t ${containerDataDir}/scripts/ {} +
`

**Comment by tashrifbillah** [comment]
A more proper find command w/o any console warning:

```
find ./ -maxdepth 1 -type f ! -name `basename $DPDASH_IMG`
```

**Comment by tashrifbillah** [comment]
And the problematic line:
https://github.com/AMP-SCZ/dpdash/blob/382018465fcb086f014b86ab6b5f52d7584361c6/singularity/init.sh#L37

reduces to:
```
cp $(find ./ -maxdepth 1 -type f ! -name `basename $DPDASH_IMG`) ${containerDataDir}/scripts/
```

I shall submit a PR.
