### ISSUE TITLE
Matrix page fails to update the matrix when a new configuration is selected

### ISSUE THREAD

**Issue by JackVCurtis** [AMP-SCZ/dpdash#693]

**Comment by justintbaker** [comment]
This is still not working for me, unless I'm missing something.  In this example, I have waited ~30 sec to 2 min and the matrix hasn't yet updated

![Image](https://github.com/AMP-SCZ/dpdash/assets/19879182/d4cfb50d-3f69-4f3d-aacc-1ed675f51b86)

When I hit refresh, this appears after 3-4 seconds:

![Image](https://github.com/AMP-SCZ/dpdash/assets/19879182/eb6a0c56-b6a0-4b06-9ff6-d48e459dc610)
