### ISSUE TITLE
initialize_ordered_bulk_op is deprecated

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/dpdash#7]
>  import.py -c examples/config.yml "/data/predict/kevin_lochness_test/PHOENIX/GENERAL/test/subject10??/mri/processed/*csv"

Warning:

```
INFO:__main__:cleaning metadata
/home/tb571/min3-dpdash/bin/import.py:109: DeprecationWarning: initialize_ordered_bulk_op is deprecated
  bulk_metadata = db.metadata.initialize_ordered_bulk_op()
```

**Comment by blms** [comment]
Will be closed by https://github.com/harvard-nrg/dpimport/pull/5

**Comment by blms** [comment]
Closed by https://github.com/PREDICT-DPACC/dpimport/pull/2
