### ISSUE TITLE
Bug loading charts

### ISSUE THREAD

**Issue by Elkrival** [AMP-SCZ/dpdash#725]
The new linting rules have reformatted pieces of the code that loads charts, and now they won't load. 

Refactor the code to follow linting rules and fix the following error.

![Image](https://github.com/AMP-SCZ/dpdash/assets/19805355/85e10e65-fa2f-4c27-a947-e1d9f6237b14)

**Comment by mikestone14** [comment]
This bug also occurs in the BarGraphTooltip (line 20), which is what causes the app to crash when hovering over the UR site.
